export const UPLOAD_IMG_GOOGLE = "UPLOAD_IMG_GOOGLE";
export const UPLOAD_IMG_GOOGLE_FAILURE = "UPLOAD_IMG_GOOGLE_FAILURE";
export const UPLOAD_IMG_GOOGLE_SUCCESS = "UPLOAD_IMG_GOOGLE_SUCCESS";

export const UPLOAD_USER_PROFILE_PICTURE = "UPLOAD_USER_PROFILE_PICTURE";
export const UPLOAD_USER_PROFILE_PICTURE_FAILURE = "UPLOAD_USER_PROFILE_PICTURE_FAILURE";
export const UPLOAD_USER_PROFILE_PICTURE_SUCCESS = "UPLOAD_USER_PROFILE_PICTURE_SUCCESS";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_FAILURE = "UPDATE_USER_PROFILE_FAILURE";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";

export const GET_VERSION = "GET_VERSION";
export const GET_VERSION_FAILURE = "GET_VERSION_FAILURE";
export const GET_VERSION_SUCCESS = "GET_VERSION_SUCCESS";

