export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";

export const RESET_PASSWORD_BY_TOKEN = "RESET_PASSWORD_BY_TOKEN";
export const RESET_PASSWORD_BY_TOKEN_FAILURE = "RESET_PASSWORD_BY_TOKEN_FAILURE";
export const RESET_PASSWORD_BY_TOKEN_SUCCESS = "RESET_PASSWORD_BY_TOKEN_SUCCESS";
