
export const GET_USER_SITTER = "GET_USER_SITTER";
export const GET_USER_SITTER_FAILURE = "GET_USER_SITTER_FAILURE";
export const GET_USER_SITTER_SUCCESS = "GET_USER_SITTER_SUCCESS";

export const GET_USER_AVAILABLE_SITTER = "GET_USER_AVAILABLE_SITTER";
export const GET_USER_AVAILABLE_SITTER_FAILURE = "GET_USER_AVAILABLE_SITTER_FAILURE";
export const GET_USER_AVAILABLE_SITTER_SUCCESS = "GET_USER_AVAILABLE_SITTER_SUCCESS";

export const UPDATE_DESC = "UPDATE_DESC";
export const UPDATE_DESC_FAILURE = "UPDATE_DESC_FAILURE";
export const UPDATE_DESC_SUCCESS = "UPDATE_DESC_SUCCESS";

export const UPDATE_RATES = "UPDATE_RATES";
export const UPDATE_RATES_FAILURE = "UPDATE_RATES_FAILURE";
export const UPDATE_RATES_SUCCESS = "UPDATE_RATES_SUCCESS";

export const UPDATE_YOE = "UPDATE_YOE";
export const UPDATE_YOE_FAILURE = "UPDATE_YOE_FAILURE";
export const UPDATE_YOE_SUCCESS = "UPDATE_YOE_SUCCESS";

export const UPDATE_SPECIAL_YOE = "UPDATE_SPECIAL_YOE";
export const UPDATE_SPECIAL_YOE_FAILURE = "UPDATE_SPECIAL_YOE_FAILURE";
export const UPDATE_SPECIAL_YOE_SUCCESS = "UPDATE_SPECIAL_YOE_SUCCESS";

export const UPDATE_CER = "UPDATE_CER";
export const UPDATE_CER_FAILURE = "UPDATE_CER_FAILURE";
export const UPDATE_CER_SUCCESS = "UPDATE_CER_SUCCESS";

export const UPDATE_TIME = "UPDATE_TIME";
export const UPDATE_TIME_FAILURE = "UPDATE_TIME_FAILURE";
export const UPDATE_TIME_SUCCESS = "UPDATE_TIME_SUCCESS";


